name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wasmerio/setup-wasmer@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.1
      - run: pnpm install
      - run: make
